repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: terraform-fmt
        name: Terraform Format
        entry: terraform fmt -check -recursive
        language: system
        pass_filenames: false

      - id: terraform-validate
        name: Terraform Validate
        entry: terraform validate
        language: system
        pass_filenames: false
